# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: docker.siemens.com/industrial-edge-sup/development/qrcode_scanner:latest

before_script:
  - echo "Before script section"


after_script:
  - echo "After script section"
  - echo "Clean up repository"
  - rm -r qrcode_scanner.git

test1:
  script:
    - echo "Copy SSH key from Variables"
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - ssh-keyscan code.siemens.com >> ~/.ssh/known_hosts
    - git clone --bare git@code.siemens.com:industrial-edge-sup/development/qrcode_scanner.git
    - cd qrcode_scanner.git
    - git push --mirror git@github.com:NormanHummel/industrial_edge_mirror.git
    